name: drama_book
description: A drama booking app demo with local database and fake APIs.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^0.4.2+2
  path: ^1.8.3
  uuid: ^4.1.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/romeo_juliet.jpg
    - assets/images/hamlet.jpeg
    - assets/images/macbeth.jpeg
    - assets/images/midsummer_night.jpeg
    - assets/images/tempest.jpg
